# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Gridded NWP weather forecast data fetcher and synchronizer."""

from multimet.weather_fetcher.config import (
    CPC_CACHE_REFRESH_HOURS,
    CPC_MAX_PUBLICATION_LAG_DAYS,
    MODEL_NATIVE_LEAD_HOURS,
    output_lead_hours,
    run_lead_hours,
    to_stored_units,
    from_stored_units,
    DEFAULT_MSLP_OFFSET_HPA,
    DEFAULT_SYNC_MODELS,
    DYNAMICAL_MODELS,
    from_stored_units,
    GLOBAL_VARS,
    GRID_DEG,
    KEEP_PREVIOUS_RUNS,
    MAX_LEAD_HOURS,
    MSLP_OFFSET_HPA,
    N_LAT,
    N_LON,
    NUM_STEPS,
    output_lead_hours,
    RUN_DATASET_TO_MODEL,
    run_lead_hours,
    RUN_METADATA_FILE,
    STAC_CATALOG_URL,
    STEP_HOURS,
    STREAM_FILES,
    STREAM_SUFFIX,
    STREAM_VARIABLES,
    SUPPORTED_MODELS,
    SUPPORTED_VARIABLES,
    SYNC_STATUS_FILE,
    to_stored_units,
)
from multimet.weather_fetcher.fetcher import (
    bilinear_sample_grid,
    compute_accumulated_precip_grid,
    compute_wind_speed_and_direction,
    extract_accumulation_series,
    extract_point_value,
    fetch_catchment_summary,
    fetch_forecast_grid,
    fetch_point_timeseries,
    fetch_wind_grid,
    file_step_for_lead,
    geometry_points,
    get_model_data_info_from_streams,
    grid_indices,
    mean_rate_grid,
    rate_file_steps,
    round_or_none,
    sample_stream_grid,
    scan_streams,
    streams_to_xarray,
    WeatherDataFetcher,
)
from multimet.weather_fetcher.sync import (
    aggregate_rates,
    current_models_metadata,
    current_run_dir,
    download_model_run,
    IncompleteRunError,
    is_plane_complete,
    latest_init_time_str,
    list_available_runs,
    load_run_metadata,
    open_dynamical_catalog,
    open_dynamical_dataset,
    prune_old_runs,
    read_json_if_exists,
    read_sync_status,
    require_data_dir,
    swap_current_symlink,
    sync_all_models,
    sync_model,
    utc_now_str,
    WeatherSynchronizer,
    write_json_atomic,
)

__all__ = [
    "CPC_CACHE_REFRESH_HOURS",
    "CPC_MAX_PUBLICATION_LAG_DAYS",
    "MODEL_NATIVE_LEAD_HOURS",
    "output_lead_hours",
    "run_lead_hours",
    "to_stored_units",
    "from_stored_units",
    "DEFAULT_MSLP_OFFSET_HPA",
    "DEFAULT_SYNC_MODELS",
    "DYNAMICAL_MODELS",
    "GLOBAL_VARS",
    "GRID_DEG",
    "IncompleteRunError",
    "KEEP_PREVIOUS_RUNS",
    "MAX_LEAD_HOURS",
    "MSLP_OFFSET_HPA",
    "NUM_STEPS",
    "N_LAT",
    "N_LON",
    "RUN_DATASET_TO_MODEL",
    "RUN_METADATA_FILE",
    "STAC_CATALOG_URL",
    "STEP_HOURS",
    "STREAM_FILES",
    "STREAM_SUFFIX",
    "STREAM_VARIABLES",
    "SUPPORTED_MODELS",
    "SUPPORTED_VARIABLES",
    "SYNC_STATUS_FILE",
    "WeatherDataFetcher",
    "WeatherSynchronizer",
    "aggregate_rates",
    "bilinear_sample_grid",
    "compute_accumulated_precip_grid",
    "compute_wind_speed_and_direction",
    "current_models_metadata",
    "current_run_dir",
    "download_model_run",
    "extract_accumulation_series",
    "extract_point_value",
    "fetch_catchment_summary",
    "fetch_forecast_grid",
    "fetch_point_timeseries",
    "fetch_wind_grid",
    "file_step_for_lead",
    "from_stored_units",
    "geometry_points",
    "get_model_data_info_from_streams",
    "grid_indices",
    "is_plane_complete",
    "latest_init_time_str",
    "list_available_runs",
    "load_run_metadata",
    "mean_rate_grid",
    "open_dynamical_catalog",
    "open_dynamical_dataset",
    "output_lead_hours",
    "prune_old_runs",
    "rate_file_steps",
    "read_json_if_exists",
    "read_sync_status",
    "require_data_dir",
    "round_or_none",
    "run_lead_hours",
    "sample_stream_grid",
    "scan_streams",
    "streams_to_xarray",
    "swap_current_symlink",
    "sync_all_models",
    "sync_model",
    "to_stored_units",
    "utc_now_str",
    "write_json_atomic",
]
