# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Models-as-a-Service (`maas`) multi-model operational flood data-fetching package.

Provides unified clients, spatial river-network indexing, upstream-area reach
snapping, return-period threshold calculators, and multi-model forecast
data fetching across:
  1. Google FloodHub (`FloodHubClient`)
  2. Copernicus GloFAS v4 (`GloFASClient`)
  3. GEOGLOWS ECMWF v2 (`GeoGLOWSClient`)
  4. JAXA Today's Earth CaMa-Flood (`TodaysEarthClient`)
"""

from maas.config import (
    CAMA_GRID_RES_DEG,
    CANONICAL_RETURN_PERIODS,
    DEFAULT_MAAS_MODELS,
    FLOODHUB_BASE_URL,
    GEOGLOWS_BASE_URL,
    GLOFAS_BASE_URL,
    GLOFAS_NLAT,
    GLOFAS_NLON,
    GLOFAS_RES_DEG,
    JAXA_STAC_CATALOG_URL,
    MAAS_MODEL_NAMES,
    MODEL_ALIASES,
    NETWORK_LABELS,
    PROVIDER_SCHEMAS,
    PROVIDERS,
    RETURN_PERIOD_YEARS,
    TODAYS_EARTH_SOURCE,
    MaaSConfig,
    convert_discharge_units,
    haversine_km,
    normalize_requested_models,
    parse_finite_float,
    parse_float_or_default,
    parse_float_or_nan,
    parse_int,
)
from maas.fetcher import (
    MaaSDataFetcher,
    MaaSEngine,
    SQLiteCache,
    align_daily_series,
    daily_series,
    fetch_forecasts,
    fetch_gauges,
    fetch_historical,
    fetch_return_periods,
    resolve_reaches,
    window_peak,
)
from maas.floodhub import (
    FloodHubClient,
    derive_floodhub_severity_from_forecast,
    geom_area_km2,
    kml_to_geometry,
    normalize_floodhub_severity,
    normalize_floodhub_trend,
    parse_floodhub_forecast_response,
    parse_floodhub_gauges_response,
)
from maas.geoglows import (
    GeoGLOWSClient,
    extract_geoglows_zarr_series,
    parse_geoglows_forecast_response,
    parse_geoglows_retrospective_response,
    parse_geoglows_return_periods_payload,
)
from maas.glofas import (
    GloFASClient,
    compute_glofas_reanalysis_return_periods,
    extract_glofas_zarr_series,
    parse_glofas_forecast_response,
)
from maas.networks import (
    FLOODHUB_LOD,
    GEOGLOWS_LOD,
    GLOFAS_LOD,
    MODELS,
    TE_LOD,
    as_linkno,
    build_geoglows_pyramid,
    build_glofas_and_te_pyramids,
    cama_cell_area_km2,
    cama_cell_id,
    cama_cell_polygon,
    extract_level_features,
    glofas_cell_center,
    glofas_cell_polygon,
    is_geoglows_river_id,
    load_geoglows_lookup,
    load_network_pyramid,
    lod_for_zoom,
    pyramid_signature,
    query_geoglows_reaches,
    query_hydrorivers_reaches,
    resolve_cross_network_click,
    save_network_pyramid,
    snap_cama_cell,
    snap_geoglows_reach_from_gpkg,
    snap_glofas_cell_from_network,
    trace_main_stem_chain,
)
from maas.thresholds import (
    EXCEEDANCE_CLASSES,
    RISK_RANK,
    UNASSESSED_COLOR,
    UNASSESSED_LABEL,
    classify_exceedance,
    compute_empirical_weibull_return_periods,
    compute_gumbel_return_periods,
    compute_return_periods,
    estimate_return_period_years,
    ev1_fit_line,
    extract_annual_maxima,
    gumbel_frequency_factor,
    gumbel_quantile_from_return_periods,
    known_return_levels,
    scaled_index_flood_return_periods,
    thresholds_from_return_periods,
)
from maas.todays_earth import (
    TODAYS_EARTH_EMULATION_NOTE,
    TodaysEarthClient,
    extract_te_series,
    format_todays_earth_forecast,
    lookup_camaflood_binary_cell,
    parse_todays_earth_payload,
)

__all__ = [
    'CAMA_GRID_RES_DEG',
    'CANONICAL_RETURN_PERIODS',
    'DEFAULT_MAAS_MODELS',
    'EXCEEDANCE_CLASSES',
    'FLOODHUB_BASE_URL',
    'FLOODHUB_LOD',
    'GEOGLOWS_BASE_URL',
    'GEOGLOWS_LOD',
    'GLOFAS_BASE_URL',
    'GLOFAS_LOD',
    'GLOFAS_NLAT',
    'GLOFAS_NLON',
    'GLOFAS_RES_DEG',
    'JAXA_STAC_CATALOG_URL',
    'MAAS_MODEL_NAMES',
    'MODELS',
    'MODEL_ALIASES',
    'NETWORK_LABELS',
    'PROVIDERS',
    'PROVIDER_SCHEMAS',
    'RETURN_PERIOD_YEARS',
    'RISK_RANK',
    'TE_LOD',
    'TODAYS_EARTH_EMULATION_NOTE',
    'TODAYS_EARTH_SOURCE',
    'UNASSESSED_COLOR',
    'UNASSESSED_LABEL',
    'FloodHubClient',
    'GeoGLOWSClient',
    'GloFASClient',
    'MaaSConfig',
    'MaaSDataFetcher',
    'MaaSEngine',
    'SQLiteCache',
    'TodaysEarthClient',
    'align_daily_series',
    'as_linkno',
    'build_geoglows_pyramid',
    'build_glofas_and_te_pyramids',
    'cama_cell_area_km2',
    'cama_cell_id',
    'cama_cell_polygon',
    'classify_exceedance',
    'compute_empirical_weibull_return_periods',
    'compute_glofas_reanalysis_return_periods',
    'compute_gumbel_return_periods',
    'compute_return_periods',
    'convert_discharge_units',
    'daily_series',
    'derive_floodhub_severity_from_forecast',
    'estimate_return_period_years',
    'ev1_fit_line',
    'extract_annual_maxima',
    'extract_geoglows_zarr_series',
    'extract_glofas_zarr_series',
    'extract_level_features',
    'extract_te_series',
    'fetch_forecasts',
    'fetch_gauges',
    'fetch_historical',
    'fetch_return_periods',
    'format_todays_earth_forecast',
    'geom_area_km2',
    'glofas_cell_center',
    'glofas_cell_polygon',
    'gumbel_frequency_factor',
    'gumbel_quantile_from_return_periods',
    'haversine_km',
    'is_geoglows_river_id',
    'kml_to_geometry',
    'known_return_levels',
    'load_geoglows_lookup',
    'load_network_pyramid',
    'lod_for_zoom',
    'lookup_camaflood_binary_cell',
    'normalize_floodhub_severity',
    'normalize_floodhub_trend',
    'normalize_requested_models',
    'parse_finite_float',
    'parse_float_or_default',
    'parse_float_or_nan',
    'parse_floodhub_forecast_response',
    'parse_floodhub_gauges_response',
    'parse_geoglows_forecast_response',
    'parse_geoglows_retrospective_response',
    'parse_geoglows_return_periods_payload',
    'parse_glofas_forecast_response',
    'parse_int',
    'parse_todays_earth_payload',
    'pyramid_signature',
    'query_geoglows_reaches',
    'query_hydrorivers_reaches',
    'resolve_cross_network_click',
    'resolve_reaches',
    'save_network_pyramid',
    'scaled_index_flood_return_periods',
    'snap_cama_cell',
    'snap_geoglows_reach_from_gpkg',
    'snap_glofas_cell_from_network',
    'thresholds_from_return_periods',
    'trace_main_stem_chain',
    'window_peak',
]
